s = "This is a Toyota"
print(s.capitalize())
print(s.swapcase())
print(s.startswith("This is"))
print(s.startswith("a ", 5, 10))
print(s.endswith("Toyota"))
print(s.index("a"))
# print(s.index("wow")) - returns error
print(s.find("a"))
print(s.find("wow")) #returns -1
print(s.center(82))
print(len(s))
print(s.title())
print(s.istitle())
print(s.isalpha())
print(s.isalnum())
print(s.isspace())
print(s.count(" "))
print(s.isprintable())
print(s.islower())
print(s.isupper())
print(s.upper())
print(s.lower())
print(s.rstrip)
print(s.split())
print(s.split("a"))